name: mcp
on: 
  workflow_dispatch: 
jobs:
  matrixj:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nums: [1,2,3,4]
      max-parallel: 1
    steps:
      - name: print matrix
        if: ${{startsWith(matrix.nums,'1')}}
        run: |
          echo ${{matrix.nums}}
    timeout-minutes: 5