name: check runner
on: 
  workflow_dispatch: 
jobs:
  check-runner:
    runs-on: ubuntu-22.04
    steps:
      - run: echo hello world
        shell: bash
      - run: |
          uname -a
          echo "Runner os:" $RUNNER_OS